# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2771a3ec83ead465b25ce4dcbc33a14f4a9a30f6501a1fbd475dededaccbc11e508c5bd0237d9f354c308332e0bbbcf68b621cfaf5f073774519780cece11cf

test:
  secret_key_base: e24b85a50b80f913f9659b9ccee6b84eb393c1d18a654269eddcd6a03de72963792dbb9e92328a94aab1c567dc88a5c78bb9e20011e14be59ce11330502299de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
